apiVersion: v1
kind: Service
metadata: 
  name: svc-portal-noticias
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 31000    
      #targetPort: 80 --> qdo nao informado assumi a msm porta de esculta    
  selector:
    app: portal-noticias